apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u0odpo9xp-nodejs 
  janus-idp.io/tekton: u0odpo9xp-nodejs
  backstage.io/kubernetes-id: u0odpo9xp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0odpo9xp-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml